# -*- coding: utf-8 -*-
"""RAG_QA_YARDSTICK

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a-M1gUBvqtpUCq8J8eiIqdUDoyA4FP_w
"""

!pip install openai==0.27.8

import google.generativeai as genai

genai.configure(api_key="AIzaSyBCiF7kzYFxWuQJ9P0oD2DcgYkEn6yDcuY")
model = genai.GenerativeModel("gemini-1.5-flash")

business_goal = input("Enter the business goal or objective: ")
target_audience = input("Enter the target audience or market: ")
extra_info = input("Enter any extra details or specific instructions: ")

prompt = f"Generate a business strategy for achieving the goal: {business_goal}. Target audience: {target_audience}. {extra_info}"

response = model.generate_content(prompt)

print(response.text)

